(define (make-account amnt passwd)
  (let ((amount amnt)
        (password passwd))
  (lambda (p cmd) 
    (cond ((not (eq? p password)) (lambda (x) "Incorrect password" ))
          ((eq? cmd 'withdraw) (lambda (x) (begin (set! amount (- amount x)) amount)))
          ((eq? cmd 'deposit) (lambda (x) (begin (set! amount (+ amount x)) amount)))
    ))
  )
)

(define acc (make-account 100 'secret-password))
((acc 'secret-password 'withdraw) 40)
((acc 'some-other-password 'deposit) 50)