 (define (or-gate a1 a2 output) 
   (let ((c (make-wire)) 
         (d (make-wire)) (e (make-wire)) 
         (f (make-wire) (g (make-wire)))) 
     (and-gate a1 a1 d) 
     (and-gate a2 a2 e) 
     (inverter d f) 
     (inverter e g) 
     (and-gate f g c) 
     (inverter c output) 
     'ok)) 